---
openapi: 3.0.0
info:
  title: Pet CRUD API
  version: 1.0.0
paths:
  '/pets':
    get:
      operationId: getPets
      responses:
        '200':
          $ref: '#/components/responses/PetListResponse'
    post:
      operationId: createPet
      requestBody:
        description: Pet object to create
        content:
          application/json: 
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '201':
          $ref: '#/components/responses/PetResponse'
  '/pets/{id}':
    parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/PetId'
    get:
      operationId: getPet
      responses:
        '200':
          $ref: '#/components/responses/PetResponse'
    delete:
      operationId: deletePet
      responses:
        '204':
          description: Deleted succesfully
components:
  schemas:
    PetId:
      type: integer
      minimum: 1
    Pet:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/PetId'
        name:
          type: string
          example: Garfield
      required:
        - name
  responses:
    PetResponse:
      description: A single pet
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
    PetListResponse:
      description: List of pets
      content:
        application/json:
          schema:
            type: object
            properties:
              pets:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'